name: Waka Readme

on:
    schedule:
        # Runs at 20:00 on Sunday
        - cron: "0 20 * * 0"
    workflow_dispatch:
jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
            - uses: athul/waka-readme@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  COMMIT_MESSAGE: Updated my stats
